spring:
  application:
    name: TravelAgencyInABox Service
    version: v1
  profiles:
    active: local
  datasource:
    url: jdbc:h2:mem:testdb;MODE=Oracle
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
github:
  url: "https://api.github.com"
  connectionTimeout: 5000
  responseTimeout: 5000
  readTimeout: 5000
  writeTimeout: 5000
